blueprint:
  name: IKEA Trådfri Sensor
  description: "## IKEA TRÅDFRI sensor (v1.08)


    Only for use with [ZHA](https://www.home-assistant.io/integrations/zha/)


    Available controls:

    - Motion detected

    - Motion no longer detected


    Available settings:

    - Nighttime hours and light level

    - Daytime hours and light level

    - Light on level (when you turn
    "
  source_url: https://github.com/trilorian/zha/blob/main/ikea-rodret_E2201_ZHA.yaml
  domain: automation
  input:
    sensor_device:
      name: Sensor
      description: IKEA Trådfri sensor to use.
      default: ""
      selector:
        entity:
          filter:
            domain: binary_sensor
            device_class: motion
          multiple: false
    on_detected_action:
      name: Motion detected action
      description: Choose action(s) to run when motion is detected.
      default: []
      selector:
        action: {}
mode: single
trigger:
  - type: motion
    platform: device
    device_id: !input sensor_device
#    entity_id: binary_sensor.ikea_of_sweden_tradfri_motion_sensor_motion
    domain: binary_sensor
    id: motion-detected
#  - platform: event
#    event_type: zha_event
#    event_data:
#      device_id: "{{ zha_remote }}"
#      command: "on"
#      cluster_id: 6
#      endpoint_id: 1
#    id: click-on-zha
#condition: []
action:
  - conditions:
      - condition: trigger
        id: motion-detected
    sequence: !input on_detected_action
