blueprint:
  name: IKEA Trådfri Sensor

  description: "## IKEA TRÅDFRI sensor (v1.09)


    Only for use with [ZHA](https://www.home-assistant.io/integrations/zha/)


    Available controls:

    - Motion detected

    - Motion no longer detected


    Available settings:

    - Nighttime hours and light level

    - Daytime hours and light level

    - Light on level (when you turn
    "

  source_url: https://github.com/trilorian/zha/blob/main/ikea-rodret_E2201_ZHA.yaml

  domain: automation

  input:
    sensor_device:
      name: Sensor
      description: IKEA Trådfri sensor to use.
      default: ""
      selector:
        entity:
          filter:
            domain: binary_sensor
            device_class: motion
          multiple: false
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: seconds

# If motion is detected within the delay, restart the script
mode: restart

max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

action:
  - service: light.turn_on
    target: !input light_target
  - wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - delay: !input no_motion_wait
  - service: light.turn_off
    target: !input light_target
